'use client';

/**
 * 案例标签管理页面
 * 
 * 功能：
 * - 查看所有案例及其标签状态
 * - 筛选：待人工确认 / AI生成 / 已完成 / 全部
 * - 编辑标签：修改 productTags / crowdTags / emotionTags
 * - 确认标签：移除"待人工确认"标记，标记为已确认
 */

import { useState, useEffect, useCallback } from 'react';
import {
  Search, Tag, AlertTriangle, CheckCircle, Loader2, Edit3, Save, X,
  ChevronLeft, ChevronRight, RefreshCw, Bot, Eye
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';

// ==================== 类型定义 ====================

interface CaseItem {
  id: string;
  title: string;
  protagonist: string | null;
  background: string | null;
  insurance_action: string | null;
  result: string | null;
  product_tags: string[] | null;
  crowd_tags: string[] | null;
  scene_tags: string[] | null;
  emotion_tags: string[] | null;
  use_count: number | null;
  metadata: { autoGeneratedTags?: boolean } | null;
  created_at: string;
  updated_at: string;
}

interface CaseStats {
  total: number;
  needs_review: number;
  auto_tagged: number;
  has_content: number;
}

// ==================== 主组件 ====================

export default function CaseManagementPage() {
  const [cases, setCases] = useState<CaseItem[]>([]);
  const [stats, setStats] = useState<CaseStats>({ total: 0, needs_review: 0, auto_tagged: 0, has_content: 0 });
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');
  const [keyword, setKeyword] = useState('');
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const pageSize = 20;

  // 编辑弹框
  const [editCase, setEditCase] = useState<CaseItem | null>(null);
  const [editProductTags, setEditProductTags] = useState('');
  const [editCrowdTags, setEditCrowdTags] = useState('');
  const [editEmotionTags, setEditEmotionTags] = useState('');
  const [saving, setSaving] = useState(false);

  // 详情弹框
  const [viewCase, setViewCase] = useState<CaseItem | null>(null);

  const fetchCases = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ filter, keyword, page: String(page), pageSize: String(pageSize) });
      const res = await fetch(`/api/cases/manage?${params}`);
      const data = await res.json();
      if (data.success) {
        setCases(data.data.cases || []);
        setTotal(data.data.total || 0);
        setStats(data.data.stats || { total: 0, needs_review: 0, auto_tagged: 0, has_content: 0 });
      }
    } catch (err) {
      console.error('查询案例失败:', err);
      toast.error('查询案例失败');
    } finally {
      setLoading(false);
    }
  }, [filter, keyword, page]);

  useEffect(() => {
    fetchCases();
  }, [fetchCases]);

  const totalPages = Math.ceil(total / pageSize);

  // 打开编辑弹框
  const handleEdit = (c: CaseItem) => {
    setEditCase(c);
    setEditProductTags((c.product_tags || []).join(', '));
    setEditCrowdTags((c.crowd_tags || []).join(', '));
    setEditEmotionTags((c.emotion_tags || []).join(', '));
  };

  // 保存标签
  const handleSave = async () => {
    if (!editCase) return;
    setSaving(true);
    try {
      const parseTags = (str: string) => str.split(/[,，]/).map(s => s.trim()).filter(Boolean);
      const productTags = parseTags(editProductTags);
      const crowdTags = parseTags(editCrowdTags);
      const emotionTags = parseTags(editEmotionTags);

      const hasReviewTag = [...productTags, ...crowdTags, ...emotionTags].includes('待人工确认');
      const shouldRemoveReview = !hasReviewTag;

      const res = await fetch('/api/cases/manage', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: editCase.id,
          productTags,
          crowdTags,
          emotionTags,
          removeReviewTag: shouldRemoveReview,
        }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success('标签更新成功');
        setEditCase(null);
        fetchCases();
      } else {
        toast.error(data.error || '更新失败');
      }
    } catch (err) {
      console.error('更新标签失败:', err);
      toast.error('更新标签失败');
    } finally {
      setSaving(false);
    }
  };

  // 确认标签（移除"待人工确认"，标记为已确认）
  const handleConfirm = async (c: CaseItem) => {
    setSaving(true);
    try {
      const cleanTags = (tags: string[] | null) => (tags || []).filter(t => t !== '待人工确认');

      const res = await fetch('/api/cases/manage', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: c.id,
          productTags: cleanTags(c.product_tags),
          crowdTags: cleanTags(c.crowd_tags),
          emotionTags: cleanTags(c.emotion_tags),
          removeReviewTag: true,
        }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success('标签已确认');
        fetchCases();
      } else {
        toast.error(data.error || '确认失败');
      }
    } catch (err) {
      console.error('确认标签失败:', err);
      toast.error('确认标签失败');
    } finally {
      setSaving(false);
    }
  };

  const hasReviewTag = (c: CaseItem) => {
    const allTags = [...(c.product_tags || []), ...(c.crowd_tags || []), ...(c.emotion_tags || [])];
    return allTags.includes('待人工确认');
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* 页面标题 */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">案例标签管理</h1>
            <p className="text-sm text-gray-500 mt-1">管理案例的产品/人群/情感标签，确认AI自动生成的标签</p>
          </div>
          <Button variant="outline" onClick={fetchCases} disabled={loading}>
            <RefreshCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
            刷新
          </Button>
        </div>

        {/* 统计卡片 */}
        <div className="grid grid-cols-4 gap-4">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-100 rounded-lg"><Tag className="h-5 w-5 text-blue-600" /></div>
                <div>
                  <p className="text-sm text-gray-500">全部案例</p>
                  <p className="text-2xl font-bold">{stats.total}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-orange-100 rounded-lg"><AlertTriangle className="h-5 w-5 text-orange-600" /></div>
                <div>
                  <p className="text-sm text-gray-500">待人工确认</p>
                  <p className="text-2xl font-bold text-orange-600">{stats.needs_review}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-purple-100 rounded-lg"><Bot className="h-5 w-5 text-purple-600" /></div>
                <div>
                  <p className="text-sm text-gray-500">AI生成标签</p>
                  <p className="text-2xl font-bold text-purple-600">{stats.auto_tagged}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-green-100 rounded-lg"><CheckCircle className="h-5 w-5 text-green-600" /></div>
                <div>
                  <p className="text-sm text-gray-500">有内容案例</p>
                  <p className="text-2xl font-bold text-green-600">{stats.has_content}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* 筛选 + 搜索 */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <Tabs value={filter} onValueChange={(v) => { setFilter(v); setPage(1); }}>
                <TabsList>
                  <TabsTrigger value="all">全部</TabsTrigger>
                  <TabsTrigger value="needs_review" className="text-orange-600">
                    待确认 ({stats.needs_review})
                  </TabsTrigger>
                  <TabsTrigger value="auto_tagged" className="text-purple-600">
                    AI生成 ({stats.auto_tagged})
                  </TabsTrigger>
                  <TabsTrigger value="complete">已完成</TabsTrigger>
                </TabsList>
              </Tabs>
              <div className="flex-1" />
              <div className="relative w-64">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <Input
                  placeholder="搜索案例标题或人物..."
                  value={keyword}
                  onChange={(e) => { setKeyword(e.target.value); setPage(1); }}
                  className="pl-9"
                />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* 案例表格 */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">
              案例列表 ({total} 条)
            </CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-6 w-6 animate-spin text-gray-400" />
                <span className="ml-2 text-gray-500">加载中...</span>
              </div>
            ) : cases.length === 0 ? (
              <div className="text-center py-12 text-gray-500">暂无案例数据</div>
            ) : (
              <>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-[300px]">案例标题</TableHead>
                      <TableHead>产品标签</TableHead>
                      <TableHead>人群标签</TableHead>
                      <TableHead>情感标签</TableHead>
                      <TableHead>状态</TableHead>
                      <TableHead className="w-[180px]">操作</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {cases.map((c) => {
                      const isReview = hasReviewTag(c);
                      const isAuto = c.metadata?.autoGeneratedTags === true;
                      return (
                        <TableRow key={c.id} className={isReview ? 'bg-orange-50' : ''}>
                          <TableCell>
                            <div className="font-medium text-sm truncate max-w-[280px]" title={c.title}>
                              {c.title}
                            </div>
                            {c.protagonist && (
                              <div className="text-xs text-gray-400 mt-1 truncate max-w-[280px]">
                                {c.protagonist}
                              </div>
                            )}
                          </TableCell>
                          <TableCell>
                            <div className="flex flex-wrap gap-1">
                              {(c.product_tags || []).length === 0 ? (
                                <span className="text-xs text-gray-300">无</span>
                              ) : (
                                (c.product_tags || []).map((tag, i) => (
                                  <Badge
                                    key={i}
                                    variant={tag === '待人工确认' ? 'destructive' : 'secondary'}
                                    className="text-xs"
                                  >
                                    {tag}
                                  </Badge>
                                ))
                              )}
                            </div>
                          </TableCell>
                          <TableCell>
                            <div className="flex flex-wrap gap-1">
                              {(c.crowd_tags || []).length === 0 ? (
                                <span className="text-xs text-gray-300">无</span>
                              ) : (
                                (c.crowd_tags || []).map((tag, i) => (
                                  <Badge
                                    key={i}
                                    variant={tag === '待人工确认' ? 'destructive' : 'outline'}
                                    className="text-xs"
                                  >
                                    {tag}
                                  </Badge>
                                ))
                              )}
                            </div>
                          </TableCell>
                          <TableCell>
                            <div className="flex flex-wrap gap-1">
                              {(c.emotion_tags || []).length === 0 ? (
                                <span className="text-xs text-gray-300">无</span>
                              ) : (
                                (c.emotion_tags || []).map((tag, i) => (
                                  <Badge
                                    key={i}
                                    variant={tag === '待人工确认' ? 'destructive' : 'outline'}
                                    className="text-xs"
                                  >
                                    {tag}
                                  </Badge>
                                ))
                              )}
                            </div>
                          </TableCell>
                          <TableCell>
                            {isReview ? (
                              <Badge variant="destructive" className="text-xs">
                                <AlertTriangle className="h-3 w-3 mr-1" />
                                待确认
                              </Badge>
                            ) : isAuto ? (
                              <Badge className="text-xs bg-purple-100 text-purple-700 hover:bg-purple-100">
                                <Bot className="h-3 w-3 mr-1" />
                                AI生成
                              </Badge>
                            ) : (
                              <Badge variant="secondary" className="text-xs bg-green-100 text-green-700 hover:bg-green-100">
                                <CheckCircle className="h-3 w-3 mr-1" />
                                已确认
                              </Badge>
                            )}
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-1">
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => setViewCase(c)}
                                title="查看详情"
                              >
                                <Eye className="h-4 w-4" />
                              </Button>
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => handleEdit(c)}
                                title="编辑标签"
                              >
                                <Edit3 className="h-4 w-4" />
                              </Button>
                              {isReview && (
                                <Button
                                  variant="outline"
                                  size="sm"
                                  onClick={() => handleConfirm(c)}
                                  disabled={saving}
                                  className="text-green-600 border-green-300 hover:bg-green-50"
                                  title="确认标签（移除待人工确认标记）"
                                >
                                  <CheckCircle className="h-4 w-4 mr-1" />
                                  确认
                                </Button>
                              )}
                            </div>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>

                {/* 分页 */}
                <div className="flex items-center justify-between mt-4">
                  <p className="text-sm text-gray-500">
                    第 {page} / {totalPages} 页，共 {total} 条
                  </p>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={page <= 1}
                      onClick={() => setPage(page - 1)}
                    >
                      <ChevronLeft className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={page >= totalPages}
                      onClick={() => setPage(page + 1)}
                    >
                      <ChevronRight className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>

      {/* 查看详情弹框 */}
      <Dialog open={!!viewCase} onOpenChange={() => setViewCase(null)}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-lg">{viewCase?.title}</DialogTitle>
          </DialogHeader>
          {viewCase && (
            <div className="space-y-4">
              {viewCase.protagonist && (
                <div>
                  <p className="text-sm font-medium text-gray-700 mb-1">人物</p>
                  <p className="text-sm text-gray-600 whitespace-pre-wrap">{viewCase.protagonist}</p>
                </div>
              )}
              {viewCase.background && (
                <div>
                  <p className="text-sm font-medium text-gray-700 mb-1">背景</p>
                  <p className="text-sm text-gray-600 whitespace-pre-wrap">{viewCase.background}</p>
                </div>
              )}
              {viewCase.insurance_action && (
                <div>
                  <p className="text-sm font-medium text-gray-700 mb-1">方案</p>
                  <p className="text-sm text-gray-600 whitespace-pre-wrap">{viewCase.insurance_action}</p>
                </div>
              )}
              {viewCase.result && (
                <div>
                  <p className="text-sm font-medium text-gray-700 mb-1">结果</p>
                  <p className="text-sm text-gray-600 whitespace-pre-wrap">{viewCase.result}</p>
                </div>
              )}
              <div className="border-t pt-4">
                <p className="text-sm font-medium text-gray-700 mb-2">标签</p>
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-gray-500 w-16">产品:</span>
                    <div className="flex flex-wrap gap-1">
                      {(viewCase.product_tags || []).map((tag, i) => (
                        <Badge key={i} variant={tag === '待人工确认' ? 'destructive' : 'secondary'} className="text-xs">{tag}</Badge>
                      ))}
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-gray-500 w-16">人群:</span>
                    <div className="flex flex-wrap gap-1">
                      {(viewCase.crowd_tags || []).map((tag, i) => (
                        <Badge key={i} variant={tag === '待人工确认' ? 'destructive' : 'outline'} className="text-xs">{tag}</Badge>
                      ))}
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-gray-500 w-16">情感:</span>
                    <div className="flex flex-wrap gap-1">
                      {(viewCase.emotion_tags || []).map((tag, i) => (
                        <Badge key={i} variant={tag === '待人工确认' ? 'destructive' : 'outline'} className="text-xs">{tag}</Badge>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
              {viewCase.metadata?.autoGeneratedTags && (
                <div className="bg-purple-50 border border-purple-200 rounded-lg p-3">
                  <div className="flex items-center gap-2 text-purple-700 text-sm">
                    <Bot className="h-4 w-4" />
                    <span className="font-medium">AI 自动生成标签</span>
                  </div>
                  <p className="text-xs text-purple-600 mt-1">此案例的标签由 LLM 自动生成，建议人工确认准确性</p>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* 编辑标签弹框 */}
      <Dialog open={!!editCase} onOpenChange={() => setEditCase(null)}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="text-lg">编辑标签</DialogTitle>
          </DialogHeader>
          {editCase && (
            <div className="space-y-4">
              <p className="text-sm text-gray-500">{editCase.title}</p>
              <div>
                <label className="text-sm font-medium text-gray-700 mb-1 block">
                  产品标签（逗号分隔）
                </label>
                <Textarea
                  value={editProductTags}
                  onChange={(e) => setEditProductTags(e.target.value)}
                  placeholder="例如：储蓄险, 少儿储蓄险, 教育金"
                  rows={2}
                />
              </div>
              <div>
                <label className="text-sm font-medium text-gray-700 mb-1 block">
                  人群标签（逗号分隔）
                </label>
                <Textarea
                  value={editCrowdTags}
                  onChange={(e) => setEditCrowdTags(e.target.value)}
                  placeholder="例如：少儿, 家庭, 中产"
                  rows={2}
                />
              </div>
              <div>
                <label className="text-sm font-medium text-gray-700 mb-1 block">
                  情感标签（逗号分隔）
                </label>
                <Textarea
                  value={editEmotionTags}
                  onChange={(e) => setEditEmotionTags(e.target.value)}
                  placeholder="例如：温馨, 理性, 专业"
                  rows={2}
                />
              </div>
              {hasReviewTag(editCase) && (
                <div className="bg-orange-50 border border-orange-200 rounded-lg p-3">
                  <p className="text-sm text-orange-700">
                    <AlertTriangle className="h-4 w-4 inline mr-1" />
                    此案例包含"待人工确认"标签，保存时将自动移除该标记
                  </p>
                </div>
              )}
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditCase(null)}>取消</Button>
            <Button onClick={handleSave} disabled={saving}>
              {saving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Save className="h-4 w-4 mr-2" />}
              保存
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
