/**
 * 10套创作范式种子数据
 * 与方案文档严格对齐：P001~P010
 * 每套范式包含：公众号7段结构 + 小红书版结构 + 素材位置映射 + 情绪曲线
 */

import { paradigmLibrary } from './paradigm-library';

export const PARADIGM_SEED_DATA = [
  // ============================================================
  // P001: 标准错位破局范式
  // ============================================================
  {
    paradigmCode: 'P001',
    paradigmName: '标准错位破局范式',
    description: '先抛出错误认知→共情接纳→点破标准错位→通俗类比→真实案例→反问→价值重构→金句收尾。适用于客户误区型文章，是保险科普最核心的范式。',
    applicableArticleTypes: ['客户误区型', 'pitfall_guide'],
    applicableIndustries: ['insurance_life', 'insurance_health', 'insurance_property', 'finance'],
    applicableSceneKeywords: ['骗人', '不靠谱', '不赔', '坑', '套路', '回本', '保额', '没用'],
    officialAccountStructure: [
      { order: 1, stepName: '错误认知', titleTemplate: '开头引入：用场景引出误区', contentRequirement: '用1个数据或真实场景引出"很多人这样认为"的现象，直接引用错误认知原话', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['很多人说', '有人觉得', '我经常听到'] },
      { order: 2, stepName: '共情接纳', titleTemplate: '共情：我特别理解你', contentRequirement: '先接纳对方的想法，表达理解和认同，建立信任感', wordRange: { min: 80, max: 150 }, required: true, fixedPhrases: ['说实话，这种想法我特别理解', '换成是我，我也可能这样想'] },
      { order: 3, stepName: '点破错位', titleTemplate: '破局：标准错位在哪里', contentRequirement: '揭示"标准错位"——不是人错了，是衡量标准错了，用2-3句话点破', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['但问题出在哪呢', '其实不是', '关键是'] },
      { order: 4, stepName: '通俗类比', titleTemplate: '类比：用生活场景解释', contentRequirement: '用日常生活的类比（买车/买房/导航等），帮助读者从熟悉场景理解正确逻辑', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['你想想', '好比', '就像'] },
      { order: 5, stepName: '真实案例', titleTemplate: '案例：真实情况是怎样的', contentRequirement: '用真实理赔案例或行业数据佐证，展现"标准转换"后的正确结果', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['我见过一个案例', '数据告诉我们'] },
      { order: 6, stepName: '反问升华', titleTemplate: '反问：如果是你呢', contentRequirement: '用反问将案例延伸到读者自身，引发换位思考', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['如果这事发生在你身上', '你会怎么选'] },
      { order: 7, stepName: '价值重构', titleTemplate: '收尾：重新定义价值', contentRequirement: '用金句重构价值认知，一句话总结核心观点，留下思考空间', wordRange: { min: 50, max: 150 }, required: true, fixedPhrases: ['所以说', '归根结底'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '痛点引入', titleTemplate: '开头痛点', contentRequirement: '用一句话引出误区，配合痛点emoji', wordRange: { min: 30, max: 60 }, emojiSuggestions: ['😱', '❌', '💢'], shortSentence: true },
      { order: 2, stepName: '共情+破局', titleTemplate: '共情+点破', contentRequirement: '先共情再点破，2-3句短句', wordRange: { min: 50, max: 100 }, emojiSuggestions: ['💡', '✨'], shortSentence: true },
      { order: 3, stepName: '类比解释', titleTemplate: '通俗类比', contentRequirement: '用最简单的一句类比，配合emoji', wordRange: { min: 40, max: 80 }, emojiSuggestions: ['🏠', '🚗', '💡'], shortSentence: true },
      { order: 4, stepName: '案例佐证', titleTemplate: '真实案例', contentRequirement: '精简案例，只保留核心结论', wordRange: { min: 60, max: 120 }, emojiSuggestions: ['📊', '📋'], shortSentence: false },
      { order: 5, stepName: '金句收尾', titleTemplate: '金句+标签', contentRequirement: '一句总结金句+行动号召+话题标签', wordRange: { min: 30, max: 80 }, emojiSuggestions: ['💪', '🎯'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '错误认知', materialTypes: ['misconception'], isPrimary: true },
      { paragraphOrder: 2, stepName: '共情接纳', materialTypes: ['fixed_phrase'], isPrimary: true },
      { paragraphOrder: 3, stepName: '点破错位', materialTypes: ['fixed_phrase', 'misconception'], isPrimary: false },
      { paragraphOrder: 4, stepName: '通俗类比', materialTypes: ['analogy'], isPrimary: true },
      { paragraphOrder: 5, stepName: '真实案例', materialTypes: ['case', 'data'], isPrimary: true },
      { paragraphOrder: 6, stepName: '反问升华', materialTypes: ['fixed_phrase', 'personal_fragment'], isPrimary: false },
      { paragraphOrder: 7, stepName: '价值重构', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '错误认知', emotion: '警醒', intensity: 7 },
      { paragraphOrder: 2, stepName: '共情接纳', emotion: '共情', intensity: 6 },
      { paragraphOrder: 3, stepName: '点破错位', emotion: '突破', intensity: 8 },
      { paragraphOrder: 4, stepName: '通俗类比', emotion: '释然', intensity: 5 },
      { paragraphOrder: 5, stepName: '真实案例', emotion: '坚定', intensity: 7 },
      { paragraphOrder: 6, stepName: '反问升华', emotion: '升华', intensity: 8 },
      { paragraphOrder: 7, stepName: '价值重构', emotion: '温暖', intensity: 6 },
    ],
    signaturePhrases: ['说实话，这种想法我特别理解', '但问题出在哪呢', '其实不是', '你想想', '如果这事发生在你身上'],
    sortOrder: 1,
    isActive: true,
    isSystem: true,
  },

  // ============================================================
  // P002: 行业反思范式
  // ============================================================
  {
    paradigmCode: 'P002',
    paradigmName: '行业反思范式',
    description: '引出行业问题→承认行业不足→区分工具与人→分析问题根源→提出改进方向→收尾升华。适用于行业/政策解读文章。',
    applicableArticleTypes: ['行业新认知型', 'authority_analysis'],
    applicableIndustries: ['insurance_life', 'insurance_health', 'insurance_property'],
    applicableSceneKeywords: ['行业', '保险行业', '从业者', '行业乱象', '监管', '政策'],
    officialAccountStructure: [
      { order: 1, stepName: '行业问题', titleTemplate: '开头：引出行业问题', contentRequirement: '用一个现象或事件引出行业存在的问题，不回避痛点', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['这个行业确实', '很多人对保险'] },
      { order: 2, stepName: '承认不足', titleTemplate: '坦诚：承认行业确实有问题', contentRequirement: '不回避、不辩护，坦诚承认行业存在的问题', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['不瞒你说', '确实存在'] },
      { order: 3, stepName: '区分工具与人', titleTemplate: '厘清：是工具的问题还是人的问题', contentRequirement: '核心区分：保险本身没有错，错在部分人的做法，用类比说明', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['不是工具的问题', '问题出在'] },
      { order: 4, stepName: '分析根源', titleTemplate: '深挖：问题出在哪', contentRequirement: '分析问题的深层原因（信息不对称/利益驱动/监管滞后等）', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['说到底', '本质上是'] },
      { order: 5, stepName: '改进方向', titleTemplate: '建设：正在变好', contentRequirement: '给出行业正在改进的方向和事实，用数据和案例佐证', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['我们从业者', '好在'] },
      { order: 6, stepName: '读者建议', titleTemplate: '实用：普通人怎么做', contentRequirement: '给普通消费者3-5条可操作的建议', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['给大家的建议', '记住这三点'] },
      { order: 7, stepName: '收尾升华', titleTemplate: '升华：对行业的信心', contentRequirement: '用一句话总结行业前景，传递信心', wordRange: { min: 50, max: 150 }, required: true, fixedPhrases: ['归根结底', '我相信'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '行业痛点', titleTemplate: '行业真相', contentRequirement: '一句话引出行业问题', wordRange: { min: 30, max: 60 }, emojiSuggestions: ['🤔', '💭'], shortSentence: true },
      { order: 2, stepName: '坦诚+厘清', titleTemplate: '说实话+厘清', contentRequirement: '承认问题+区分工具和人', wordRange: { min: 50, max: 100 }, emojiSuggestions: ['💡', '⚖️'], shortSentence: true },
      { order: 3, stepName: '根源+改进', titleTemplate: '根因+变化', contentRequirement: '简述根因+正在变好的事实', wordRange: { min: 60, max: 120 }, emojiSuggestions: ['🔍', '📈'], shortSentence: false },
      { order: 4, stepName: '实用建议', titleTemplate: '避坑指南', contentRequirement: '3条简短建议', wordRange: { min: 40, max: 80 }, emojiSuggestions: ['✅', '📌'], shortSentence: true },
      { order: 5, stepName: '金句收尾', titleTemplate: '信心+标签', contentRequirement: '一句话传递信心+话题标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['💪', '🌟'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '行业问题', materialTypes: ['case', 'misconception'], isPrimary: true },
      { paragraphOrder: 2, stepName: '承认不足', materialTypes: ['personal_fragment'], isPrimary: true },
      { paragraphOrder: 3, stepName: '区分工具与人', materialTypes: ['analogy', 'fixed_phrase'], isPrimary: true },
      { paragraphOrder: 4, stepName: '分析根源', materialTypes: ['data', 'case'], isPrimary: true },
      { paragraphOrder: 5, stepName: '改进方向', materialTypes: ['data', 'case'], isPrimary: false },
      { paragraphOrder: 6, stepName: '读者建议', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 7, stepName: '收尾升华', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '行业问题', emotion: '质疑', intensity: 7 },
      { paragraphOrder: 2, stepName: '承认不足', emotion: '坦诚', intensity: 6 },
      { paragraphOrder: 3, stepName: '区分工具与人', emotion: '理性', intensity: 5 },
      { paragraphOrder: 4, stepName: '分析根源', emotion: '建设性', intensity: 6 },
      { paragraphOrder: 5, stepName: '改进方向', emotion: '希望', intensity: 7 },
      { paragraphOrder: 6, stepName: '读者建议', emotion: '务实', intensity: 5 },
      { paragraphOrder: 7, stepName: '收尾升华', emotion: '温暖', intensity: 6 },
    ],
    signaturePhrases: ['这个行业确实', '不是工具的问题', '说到底', '我们从业者', '好在'],
    sortOrder: 2,
    isActive: true,
    isSystem: true,
  },

  // ============================================================
  // P003: 案例归谬范式
  // ============================================================
  {
    paradigmCode: 'P003',
    paradigmName: '案例归谬范式',
    description: '抛出错误观点→讲述反面案例→用案例归谬错误观点→给出正确结论→收尾。适用于客户案例分析文章。',
    applicableArticleTypes: ['客户误区型', '事件驱动型', 'story_driven'],
    applicableIndustries: ['insurance_life', 'insurance_health'],
    applicableSceneKeywords: ['案例', '真实故事', '不赔', '拒赔', '教训'],
    officialAccountStructure: [
      { order: 1, stepName: '错误观点', titleTemplate: '开头：一种常见的错误想法', contentRequirement: '抛出错误观点，引起共鸣', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['很多人说', '经常有人问我'] },
      { order: 2, stepName: '反面案例', titleTemplate: '案例：真实发生的事', contentRequirement: '讲述一个反面的真实案例，细节丰富', wordRange: { min: 300, max: 500 }, required: true, fixedPhrases: ['你看这个案例', '去年有个客户'] },
      { order: 3, stepName: '归谬分析', titleTemplate: '归谬：案例说明了什么', contentRequirement: '用案例结果归谬错误观点，逻辑清晰', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['结果呢', '这不就说明'] },
      { order: 4, stepName: '正确结论', titleTemplate: '真相：正确的做法', contentRequirement: '给出正确认知和可操作的建议', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['所以真正', '正确的做法是'] },
      { order: 5, stepName: '类比佐证', titleTemplate: '类比：换个角度看', contentRequirement: '用类比帮助读者从另一个角度理解', wordRange: { min: 150, max: 300 }, required: false, fixedPhrases: ['打个比方', '就好比'] },
      { order: 6, stepName: '行动建议', titleTemplate: '行动：你该怎么做', contentRequirement: '给3-5条具体行动建议', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['建议大家', '记住这三点'] },
      { order: 7, stepName: '金句收尾', titleTemplate: '收尾：一句话总结', contentRequirement: '金句总结核心观点', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['所以说', '归根结底'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '错误观点', titleTemplate: '常见误区', contentRequirement: '一句话引出错误想法', wordRange: { min: 20, max: 50 }, emojiSuggestions: ['❌', '🤔'], shortSentence: true },
      { order: 2, stepName: '案例+归谬', titleTemplate: '真实案例', contentRequirement: '精简案例+归谬', wordRange: { min: 80, max: 150 }, emojiSuggestions: ['😱', '📉'], shortSentence: false },
      { order: 3, stepName: '正确做法', titleTemplate: '正确做法', contentRequirement: '正确结论+类比', wordRange: { min: 50, max: 100 }, emojiSuggestions: ['✅', '💡'], shortSentence: true },
      { order: 4, stepName: '行动建议', titleTemplate: '避坑指南', contentRequirement: '3条简短建议', wordRange: { min: 40, max: 80 }, emojiSuggestions: ['📌', '🎯'], shortSentence: true },
      { order: 5, stepName: '金句收尾', titleTemplate: '金句+标签', contentRequirement: '金句+标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['💪', '⭐'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '错误观点', materialTypes: ['misconception'], isPrimary: true },
      { paragraphOrder: 2, stepName: '反面案例', materialTypes: ['case'], isPrimary: true },
      { paragraphOrder: 3, stepName: '归谬分析', materialTypes: ['fixed_phrase', 'data'], isPrimary: true },
      { paragraphOrder: 4, stepName: '正确结论', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 5, stepName: '类比佐证', materialTypes: ['analogy'], isPrimary: true },
      { paragraphOrder: 6, stepName: '行动建议', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 7, stepName: '金句收尾', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '错误观点', emotion: '警醒', intensity: 6 },
      { paragraphOrder: 2, stepName: '反面案例', emotion: '惋惜', intensity: 8 },
      { paragraphOrder: 3, stepName: '归谬分析', emotion: '顿悟', intensity: 7 },
      { paragraphOrder: 4, stepName: '正确结论', emotion: '坚定', intensity: 7 },
      { paragraphOrder: 5, stepName: '类比佐证', emotion: '释然', intensity: 5 },
      { paragraphOrder: 6, stepName: '行动建议', emotion: '务实', intensity: 5 },
      { paragraphOrder: 7, stepName: '金句收尾', emotion: '温暖', intensity: 6 },
    ],
    signaturePhrases: ['你看这个案例', '结果呢', '这不就说明', '所以真正', '记住这三点'],
    sortOrder: 3,
    isActive: true,
    isSystem: true,
  },

  // ============================================================
  // P004: 本质定义范式
  // ============================================================
  {
    paradigmCode: 'P004',
    paradigmName: '本质定义范式',
    description: '抛出常见错误定义→拆解错误定义的问题→给出正确的本质定义→用类比解释→案例佐证→收尾。适用于保险概念科普文章。',
    applicableArticleTypes: ['客户误区型', '行业新认知型', 'free_creation'],
    applicableIndustries: ['insurance_life', 'insurance_health', 'finance'],
    applicableSceneKeywords: ['是什么', '定义', '本质', '到底', '真正', '概念'],
    officialAccountStructure: [
      { order: 1, stepName: '错误定义', titleTemplate: '开头：多数人的理解', contentRequirement: '抛出大众对某个概念的常见错误理解', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['很多人以为', '大部分人觉得'] },
      { order: 2, stepName: '拆解问题', titleTemplate: '拆解：这个理解错在哪', contentRequirement: '拆解错误定义的3个具体问题', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['但实际上', '问题在于'] },
      { order: 3, stepName: '本质定义', titleTemplate: '揭示：真正的定义', contentRequirement: '给出正确的本质定义，1-2句话说清楚', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['真正的定义是', '本质上是'] },
      { order: 4, stepName: '类比解释', titleTemplate: '类比：用生活场景解释', contentRequirement: '用日常生活类比帮助理解本质', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['打个比方', '就好比'] },
      { order: 5, stepName: '案例佐证', titleTemplate: '案例：真实情况', contentRequirement: '用真实案例佐证正确定义', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['举个真实的例子', '我遇到过'] },
      { order: 6, stepName: '价值延伸', titleTemplate: '延伸：理解了本质有什么用', contentRequirement: '从本质定义延伸出实用价值', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['理解了这一点', '你就会发现'] },
      { order: 7, stepName: '金句收尾', titleTemplate: '收尾：一句话总结', contentRequirement: '金句总结', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['归根结底', '说到底'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '错误认知', titleTemplate: '误区', contentRequirement: '一句话引出错误理解', wordRange: { min: 20, max: 50 }, emojiSuggestions: ['❌', '🤔'], shortSentence: true },
      { order: 2, stepName: '本质+类比', titleTemplate: '真相+类比', contentRequirement: '正确定义+生活类比', wordRange: { min: 60, max: 120 }, emojiSuggestions: ['💡', '🎯'], shortSentence: false },
      { order: 3, stepName: '案例+价值', titleTemplate: '案例+价值', contentRequirement: '简短案例+实用价值', wordRange: { min: 50, max: 100 }, emojiSuggestions: ['📋', '✨'], shortSentence: true },
      { order: 4, stepName: '金句收尾', titleTemplate: '金句+标签', contentRequirement: '金句+标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['💪', '🌟'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '错误定义', materialTypes: ['misconception'], isPrimary: true },
      { paragraphOrder: 2, stepName: '拆解问题', materialTypes: ['data', 'fixed_phrase'], isPrimary: false },
      { paragraphOrder: 3, stepName: '本质定义', materialTypes: ['fixed_phrase'], isPrimary: true },
      { paragraphOrder: 4, stepName: '类比解释', materialTypes: ['analogy'], isPrimary: true },
      { paragraphOrder: 5, stepName: '案例佐证', materialTypes: ['case', 'data'], isPrimary: true },
      { paragraphOrder: 6, stepName: '价值延伸', materialTypes: ['fixed_phrase', 'personal_fragment'], isPrimary: false },
      { paragraphOrder: 7, stepName: '金句收尾', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '错误定义', emotion: '困惑', intensity: 5 },
      { paragraphOrder: 2, stepName: '拆解问题', emotion: '恍然', intensity: 6 },
      { paragraphOrder: 3, stepName: '本质定义', emotion: '清晰', intensity: 7 },
      { paragraphOrder: 4, stepName: '类比解释', emotion: '释然', intensity: 5 },
      { paragraphOrder: 5, stepName: '案例佐证', emotion: '确信', intensity: 7 },
      { paragraphOrder: 6, stepName: '价值延伸', emotion: '实用', intensity: 5 },
      { paragraphOrder: 7, stepName: '金句收尾', emotion: '温暖', intensity: 6 },
    ],
    signaturePhrases: ['很多人以为', '但实际上', '真正的定义是', '打个比方', '理解了这一点'],
    sortOrder: 4,
    isActive: true,
    isSystem: true,
  },

  // ============================================================
  // P005: 热点事件范式
  // ============================================================
  {
    paradigmCode: 'P005',
    paradigmName: '热点事件范式',
    description: '引出热点事件→分析事件中的保险相关问题→给出正确的应对方式→延伸到普遍情况→收尾。适用于热点结合保险的文章。',
    applicableArticleTypes: ['事件驱动型', 'hot_event'],
    applicableIndustries: ['insurance_life', 'insurance_health', 'insurance_property'],
    applicableSceneKeywords: ['新闻', '热点', '事件', '最近', '刚发生'],
    officialAccountStructure: [
      { order: 1, stepName: '热点引入', titleTemplate: '开头：最近发生了一件事', contentRequirement: '简洁叙述热点事件，引出保险相关话题', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['最近有个新闻', '前几天看到'] },
      { order: 2, stepName: '保险分析', titleTemplate: '分析：这件事和保险有什么关系', contentRequirement: '分析事件中的保险相关问题，找到切入点', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['这件事告诉我们', '关键是'] },
      { order: 3, stepName: '正确应对', titleTemplate: '应对：正确的做法是什么', contentRequirement: '给出正确的保险应对方式，用数据或法规佐证', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['正确的做法是', '应该'] },
      { order: 4, stepName: '类比理解', titleTemplate: '类比：用生活场景帮助理解', contentRequirement: '用日常生活类比帮助理解保险逻辑', wordRange: { min: 150, max: 300 }, required: false, fixedPhrases: ['就好比', '就像'] },
      { order: 5, stepName: '普遍延伸', titleTemplate: '延伸：不只是这个案例', contentRequirement: '从个案延伸到普遍情况，让更多读者产生共鸣', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['不只是这个案例', '很多人都有'] },
      { order: 6, stepName: '行动建议', titleTemplate: '建议：普通人怎么做', contentRequirement: '给3-5条具体建议', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['建议大家', '如果是我'] },
      { order: 7, stepName: '金句收尾', titleTemplate: '收尾：总结核心观点', contentRequirement: '金句总结', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['归根结底', '所以说'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '热点引入', titleTemplate: '热点事件', contentRequirement: '一句话引出热点', wordRange: { min: 30, max: 60 }, emojiSuggestions: ['🔥', '📰'], shortSentence: true },
      { order: 2, stepName: '保险分析+应对', titleTemplate: '分析+做法', contentRequirement: '简要分析+正确做法', wordRange: { min: 60, max: 120 }, emojiSuggestions: ['💡', '✅'], shortSentence: false },
      { order: 3, stepName: '延伸+建议', titleTemplate: '延伸+建议', contentRequirement: '延伸普遍情况+简短建议', wordRange: { min: 50, max: 100 }, emojiSuggestions: ['📌', '🎯'], shortSentence: true },
      { order: 4, stepName: '金句收尾', titleTemplate: '金句+标签', contentRequirement: '金句+标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['💪', '⭐'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '热点引入', materialTypes: ['case', 'data'], isPrimary: true },
      { paragraphOrder: 2, stepName: '保险分析', materialTypes: ['misconception', 'data'], isPrimary: true },
      { paragraphOrder: 3, stepName: '正确应对', materialTypes: ['fixed_phrase', 'data'], isPrimary: false },
      { paragraphOrder: 4, stepName: '类比理解', materialTypes: ['analogy'], isPrimary: true },
      { paragraphOrder: 5, stepName: '普遍延伸', materialTypes: ['case', 'misconception'], isPrimary: false },
      { paragraphOrder: 6, stepName: '行动建议', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 7, stepName: '金句收尾', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '热点引入', emotion: '关注', intensity: 8 },
      { paragraphOrder: 2, stepName: '保险分析', emotion: '分析', intensity: 6 },
      { paragraphOrder: 3, stepName: '正确应对', emotion: '行动', intensity: 7 },
      { paragraphOrder: 4, stepName: '类比理解', emotion: '释然', intensity: 5 },
      { paragraphOrder: 5, stepName: '普遍延伸', emotion: '警醒', intensity: 7 },
      { paragraphOrder: 6, stepName: '行动建议', emotion: '务实', intensity: 5 },
      { paragraphOrder: 7, stepName: '金句收尾', emotion: '温暖', intensity: 6 },
    ],
    signaturePhrases: ['最近有个新闻', '这件事告诉我们', '如果是你', '不只是这个案例', '建议大家'],
    sortOrder: 5,
    isActive: true,
    isSystem: true,
  },

  // ============================================================
  // P006~P010: 其余5套范式（结构完整但篇幅精简）
  // ============================================================
  {
    paradigmCode: 'P006',
    paradigmName: '产品解读范式',
    description: '介绍产品基本信息→分析产品优势→分析产品不足→适合人群→不适合人群→购买建议。适用于产品测评文章。',
    applicableArticleTypes: ['行业新认知型', 'product_eval'],
    applicableIndustries: ['insurance_life', 'insurance_health'],
    applicableSceneKeywords: ['测评', '产品', '对比', '哪款好', '值得买'],
    officialAccountStructure: [
      { order: 1, stepName: '产品信息', titleTemplate: '开头：先说结论', contentRequirement: '1-2句话概括测评结论，再简要介绍产品', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['先说结论', '这款产品'] },
      { order: 2, stepName: '产品优势', titleTemplate: '优点：值得肯定的地方', contentRequirement: '列出2-3个核心优势，用数据佐证', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['优点是', '亮点在于'] },
      { order: 3, stepName: '产品不足', titleTemplate: '不足：需要注意的地方', contentRequirement: '坦诚指出2-3个不足，用类比帮助理解复杂条款', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['但要注意', '坑点在'] },
      { order: 4, stepName: '适合人群', titleTemplate: '适合：哪些人可以考虑', contentRequirement: '明确适合人群画像和购买理由', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['适合', '如果你是'] },
      { order: 5, stepName: '不适合人群', titleTemplate: '不适合：哪些人要慎重', contentRequirement: '明确不建议购买的人群和原因', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['不建议', '如果你是'] },
      { order: 6, stepName: '购买建议', titleTemplate: '建议：怎么买最划算', contentRequirement: '给出具体购买建议和注意事项', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['我的建议是', '记住'] },
      { order: 7, stepName: '金句收尾', titleTemplate: '收尾：一句话总结', contentRequirement: '金句总结选购核心逻辑', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['归根结底', '选保险'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '结论+产品', titleTemplate: '先说结论', contentRequirement: '一句话结论+产品简介', wordRange: { min: 30, max: 60 }, emojiSuggestions: ['📊', '🔍'], shortSentence: true },
      { order: 2, stepName: '优缺点', titleTemplate: '优缺点', contentRequirement: '精简优缺点', wordRange: { min: 60, max: 120 }, emojiSuggestions: ['✅', '⚠️'], shortSentence: false },
      { order: 3, stepName: '人群推荐', titleTemplate: '人群推荐', contentRequirement: '适合/不适合', wordRange: { min: 40, max: 80 }, emojiSuggestions: ['👥', '🎯'], shortSentence: true },
      { order: 4, stepName: '金句收尾', titleTemplate: '金句+标签', contentRequirement: '金句+标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['💪', '⭐'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '产品信息', materialTypes: ['data'], isPrimary: true },
      { paragraphOrder: 2, stepName: '产品优势', materialTypes: ['data', 'analogy'], isPrimary: false },
      { paragraphOrder: 3, stepName: '产品不足', materialTypes: ['misconception', 'analogy'], isPrimary: true },
      { paragraphOrder: 4, stepName: '适合人群', materialTypes: ['case'], isPrimary: false },
      { paragraphOrder: 5, stepName: '不适合人群', materialTypes: ['misconception'], isPrimary: false },
      { paragraphOrder: 6, stepName: '购买建议', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 7, stepName: '金句收尾', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '产品信息', emotion: '客观', intensity: 4 },
      { paragraphOrder: 2, stepName: '产品优势', emotion: '肯定', intensity: 6 },
      { paragraphOrder: 3, stepName: '产品不足', emotion: '谨慎', intensity: 7 },
      { paragraphOrder: 4, stepName: '适合人群', emotion: '务实', intensity: 5 },
      { paragraphOrder: 5, stepName: '不适合人群', emotion: '坦诚', intensity: 6 },
      { paragraphOrder: 6, stepName: '购买建议', emotion: '建议', intensity: 5 },
      { paragraphOrder: 7, stepName: '金句收尾', emotion: '温暖', intensity: 5 },
    ],
    signaturePhrases: ['先说结论', '优点是', '但要注意', '适合', '不建议'],
    sortOrder: 6,
    isActive: true,
    isSystem: true,
  },
  {
    paradigmCode: 'P007',
    paradigmName: '个人经历范式',
    description: '讲述自己的亲身经历→从经历中得到的感悟→延伸到保险的价值→收尾升华。适用于亲身经历分享文章。',
    applicableArticleTypes: ['客户误区型', '事件驱动型', 'story_driven'],
    applicableIndustries: ['insurance_life', 'insurance_health'],
    applicableSceneKeywords: ['我的经历', '亲身', '我自己', '那次'],
    officialAccountStructure: [
      { order: 1, stepName: '亲身经历', titleTemplate: '开头：我的一件事', contentRequirement: '讲述自己的亲身经历，细节丰富，引发共鸣', wordRange: { min: 300, max: 500 }, required: true, fixedPhrases: ['我自己', '那年'] },
      { order: 2, stepName: '感悟', titleTemplate: '感悟：这件事让我明白', contentRequirement: '从经历中提炼感悟，真情实感', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['那次之后', '我才真正明白'] },
      { order: 3, stepName: '保险价值', titleTemplate: '延伸：保险在这个场景的价值', contentRequirement: '将感悟延伸到保险的价值和意义', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['所以我说', '这就是为什么'] },
      { order: 4, stepName: '类比佐证', titleTemplate: '佐证：不是只有我', contentRequirement: '用类比或数据佐证这不是个别现象', wordRange: { min: 100, max: 200 }, required: false, fixedPhrases: ['不只是我', '很多人都有'] },
      { order: 5, stepName: '避坑提醒', titleTemplate: '提醒：你可能会踩的坑', contentRequirement: '从经历中总结1-2个避坑要点', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['如果你也遇到', '记住'] },
      { order: 6, stepName: '行动建议', titleTemplate: '建议：你可以这么做', contentRequirement: '给读者具体的行动建议', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['我的建议是', '你可以'] },
      { order: 7, stepName: '收尾升华', titleTemplate: '升华：一句话感悟', contentRequirement: '金句升华', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['说到底', '我常想'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '经历', titleTemplate: '我的故事', contentRequirement: '精简亲身经历', wordRange: { min: 60, max: 120 }, emojiSuggestions: ['📖', '💭'], shortSentence: false },
      { order: 2, stepName: '感悟+价值', titleTemplate: '感悟+价值', contentRequirement: '感悟+保险价值', wordRange: { min: 50, max: 100 }, emojiSuggestions: ['💡', '❤️'], shortSentence: true },
      { order: 3, stepName: '建议', titleTemplate: '建议', contentRequirement: '简短行动建议', wordRange: { min: 30, max: 60 }, emojiSuggestions: ['📌', '✅'], shortSentence: true },
      { order: 4, stepName: '金句收尾', titleTemplate: '金句+标签', contentRequirement: '金句+标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['💪', '🌟'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '亲身经历', materialTypes: ['case', 'personal_fragment'], isPrimary: true },
      { paragraphOrder: 2, stepName: '感悟', materialTypes: ['personal_fragment', 'fixed_phrase'], isPrimary: true },
      { paragraphOrder: 3, stepName: '保险价值', materialTypes: ['fixed_phrase', 'analogy'], isPrimary: false },
      { paragraphOrder: 4, stepName: '类比佐证', materialTypes: ['analogy', 'data'], isPrimary: false },
      { paragraphOrder: 5, stepName: '避坑提醒', materialTypes: ['misconception'], isPrimary: true },
      { paragraphOrder: 6, stepName: '行动建议', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 7, stepName: '收尾升华', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '亲身经历', emotion: '叙事', intensity: 7 },
      { paragraphOrder: 2, stepName: '感悟', emotion: '感悟', intensity: 8 },
      { paragraphOrder: 3, stepName: '保险价值', emotion: '升华', intensity: 7 },
      { paragraphOrder: 4, stepName: '类比佐证', emotion: '理性', intensity: 5 },
      { paragraphOrder: 5, stepName: '避坑提醒', emotion: '警醒', intensity: 6 },
      { paragraphOrder: 6, stepName: '行动建议', emotion: '务实', intensity: 5 },
      { paragraphOrder: 7, stepName: '收尾升华', emotion: '坚定', intensity: 7 },
    ],
    signaturePhrases: ['我自己', '那次之后', '我才真正明白', '所以我说', '如果你也遇到'],
    sortOrder: 7,
    isActive: true,
    isSystem: true,
  },
  {
    paradigmCode: 'P008',
    paradigmName: '避坑指南范式',
    description: '引出某类保险的常见问题→逐条讲解每个坑的表现和危害→给出避坑方法→收尾。适用于避坑干货文章。',
    applicableArticleTypes: ['客户误区型', 'pitfall_guide'],
    applicableIndustries: ['insurance_life', 'insurance_health', 'insurance_property'],
    applicableSceneKeywords: ['避坑', '坑', '踩坑', '误区', '注意', '不要'],
    officialAccountStructure: [
      { order: 1, stepName: '常见问题', titleTemplate: '开头：这类保险的坑', contentRequirement: '引出某类保险的常见问题，说明普遍性', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['很多人踩过', '这类保险'] },
      { order: 2, stepName: '坑1', titleTemplate: '第一个坑：XX的表现', contentRequirement: '详细讲解第一个坑的表现和危害', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['第一个坑', '最常见的'] },
      { order: 3, stepName: '坑2', titleTemplate: '第二个坑：XX的表现', contentRequirement: '详细讲解第二个坑', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['第二个坑', '另一个常见'] },
      { order: 4, stepName: '坑3+类比', titleTemplate: '第三个坑+类比', contentRequirement: '第三个坑用类比帮助理解', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['第三个坑', '就好比'] },
      { order: 5, stepName: '避坑方法', titleTemplate: '避坑：怎么避免', contentRequirement: '给出3-5条避坑方法', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['怎么避免', '记住这三点'] },
      { order: 6, stepName: '案例佐证', titleTemplate: '佐证：避坑成功的案例', contentRequirement: '用真实案例佐证避坑方法的有效性', wordRange: { min: 100, max: 200 }, required: false, fixedPhrases: ['我见过', '有个客户'] },
      { order: 7, stepName: '金句收尾', titleTemplate: '收尾：一句话总结', contentRequirement: '金句总结避坑核心', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['归根结底', '所以'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '问题引入', titleTemplate: '避坑预警', contentRequirement: '一句话引出问题', wordRange: { min: 20, max: 50 }, emojiSuggestions: ['⚠️', '🚨'], shortSentence: true },
      { order: 2, stepName: '坑点列表', titleTemplate: '3个坑', contentRequirement: '精简3个坑点', wordRange: { min: 80, max: 150 }, emojiSuggestions: ['❌', '❌', '❌'], shortSentence: true },
      { order: 3, stepName: '避坑方法', titleTemplate: '避坑方法', contentRequirement: '3条避坑方法', wordRange: { min: 40, max: 80 }, emojiSuggestions: ['✅', '✅', '✅'], shortSentence: true },
      { order: 4, stepName: '金句收尾', titleTemplate: '金句+标签', contentRequirement: '金句+标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['💪', '⭐'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '常见问题', materialTypes: ['misconception'], isPrimary: true },
      { paragraphOrder: 2, stepName: '坑1', materialTypes: ['misconception', 'case'], isPrimary: true },
      { paragraphOrder: 3, stepName: '坑2', materialTypes: ['misconception', 'data'], isPrimary: true },
      { paragraphOrder: 4, stepName: '坑3+类比', materialTypes: ['misconception', 'analogy'], isPrimary: true },
      { paragraphOrder: 5, stepName: '避坑方法', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 6, stepName: '案例佐证', materialTypes: ['case'], isPrimary: false },
      { paragraphOrder: 7, stepName: '金句收尾', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '常见问题', emotion: '警醒', intensity: 7 },
      { paragraphOrder: 2, stepName: '坑1', emotion: '细节', intensity: 6 },
      { paragraphOrder: 3, stepName: '坑2', emotion: '警醒', intensity: 7 },
      { paragraphOrder: 4, stepName: '坑3+类比', emotion: '释然', intensity: 5 },
      { paragraphOrder: 5, stepName: '避坑方法', emotion: '安心', intensity: 6 },
      { paragraphOrder: 6, stepName: '案例佐证', emotion: '确信', intensity: 6 },
      { paragraphOrder: 7, stepName: '金句收尾', emotion: '温暖', intensity: 5 },
    ],
    signaturePhrases: ['很多人踩过', '第一个坑', '第二个坑', '怎么避免', '记住这三点'],
    sortOrder: 8,
    isActive: true,
    isSystem: true,
  },
  {
    paradigmCode: 'P009',
    paradigmName: '对比分析范式',
    description: '介绍两种不同的选择→分别分析各自的优缺点→给出不同情况下的选择建议→收尾。适用于产品/方案对比文章。',
    applicableArticleTypes: ['行业新认知型', 'comparative_analysis', 'product_eval'],
    applicableIndustries: ['insurance_life', 'insurance_health'],
    applicableSceneKeywords: ['对比', '哪个好', '怎么选', '区别', 'A还是B'],
    officialAccountStructure: [
      { order: 1, stepName: '两种选择', titleTemplate: '开头：两种方案', contentRequirement: '引出两种常见的保险选择/方案', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['两种方案', '很多人纠结'] },
      { order: 2, stepName: 'A方案分析', titleTemplate: '先看A方案', contentRequirement: '客观分析A方案的优缺点', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['先看', '优势是'] },
      { order: 3, stepName: 'B方案分析', titleTemplate: '再看B方案', contentRequirement: '客观分析B方案的优缺点', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['再看', '好处是'] },
      { order: 4, stepName: '对比类比', titleTemplate: '类比：用生活场景对比', contentRequirement: '用类比帮助理解两者本质区别', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['就好比', '差异在于'] },
      { order: 5, stepName: '选择建议', titleTemplate: '建议：怎么选', contentRequirement: '按不同情况给出选择建议', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['怎么选', '关键看'] },
      { order: 6, stepName: '避坑提醒', titleTemplate: '提醒：选错了会怎样', contentRequirement: '用案例说明选错的后果', wordRange: { min: 100, max: 200 }, required: true, fixedPhrases: ['选错了', '我见过'] },
      { order: 7, stepName: '金句收尾', titleTemplate: '收尾：选保险的核心逻辑', contentRequirement: '金句总结选择逻辑', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['归根结底', '没有最好'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '两种选择', titleTemplate: 'A还是B', contentRequirement: '引出两种选择', wordRange: { min: 20, max: 50 }, emojiSuggestions: ['🤔', '⚖️'], shortSentence: true },
      { order: 2, stepName: '对比+建议', titleTemplate: '对比+建议', contentRequirement: '精简对比+选择建议', wordRange: { min: 60, max: 120 }, emojiSuggestions: ['📊', '💡'], shortSentence: false },
      { order: 3, stepName: '避坑+金句', titleTemplate: '避坑+金句', contentRequirement: '简短避坑提醒+金句', wordRange: { min: 30, max: 80 }, emojiSuggestions: ['⚠️', '💪'], shortSentence: true },
      { order: 4, stepName: '标签收尾', titleTemplate: '标签', contentRequirement: '话题标签', wordRange: { min: 10, max: 40 }, emojiSuggestions: ['📌'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '两种选择', materialTypes: ['misconception'], isPrimary: false },
      { paragraphOrder: 2, stepName: 'A方案分析', materialTypes: ['data', 'case'], isPrimary: true },
      { paragraphOrder: 3, stepName: 'B方案分析', materialTypes: ['data', 'case'], isPrimary: true },
      { paragraphOrder: 4, stepName: '对比类比', materialTypes: ['analogy'], isPrimary: true },
      { paragraphOrder: 5, stepName: '选择建议', materialTypes: ['fixed_phrase'], isPrimary: false },
      { paragraphOrder: 6, stepName: '避坑提醒', materialTypes: ['misconception', 'case'], isPrimary: true },
      { paragraphOrder: 7, stepName: '金句收尾', materialTypes: ['golden_sentence'], isPrimary: true },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '两种选择', emotion: '客观', intensity: 4 },
      { paragraphOrder: 2, stepName: 'A方案分析', emotion: '分析', intensity: 5 },
      { paragraphOrder: 3, stepName: 'B方案分析', emotion: '分析', intensity: 5 },
      { paragraphOrder: 4, stepName: '对比类比', emotion: '权衡', intensity: 6 },
      { paragraphOrder: 5, stepName: '选择建议', emotion: '建议', intensity: 6 },
      { paragraphOrder: 6, stepName: '避坑提醒', emotion: '警醒', intensity: 7 },
      { paragraphOrder: 7, stepName: '金句收尾', emotion: '温暖', intensity: 5 },
    ],
    signaturePhrases: ['两种方案', '先看', '再看', '怎么选', '关键看'],
    sortOrder: 9,
    isActive: true,
    isSystem: true,
  },
  {
    paradigmCode: 'P010',
    paradigmName: '年终总结范式',
    description: '回顾过去一年的行业变化→总结自己的感悟→对未来的展望→给读者的建议→收尾。适用于年度回顾文章。',
    applicableArticleTypes: ['行业新认知型', 'free_creation'],
    applicableIndustries: ['insurance_life', 'insurance_health', 'insurance_property', 'finance'],
    applicableSceneKeywords: ['年终', '回顾', '总结', '一年', '2024', '2025'],
    officialAccountStructure: [
      { order: 1, stepName: '行业变化', titleTemplate: '开头：这一年发生了什么', contentRequirement: '回顾过去一年的行业重大变化', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['回顾这一年', '最大的变化'] },
      { order: 2, stepName: '个人感悟', titleTemplate: '感悟：我的感受', contentRequirement: '分享个人的从业感悟', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['我个人的感受', '让我感触最深'] },
      { order: 3, stepName: '未来展望', titleTemplate: '展望：未来会怎样', contentRequirement: '对行业未来趋势的判断', wordRange: { min: 150, max: 300 }, required: true, fixedPhrases: ['展望未来', '我觉得'] },
      { order: 4, stepName: '给读者建议', titleTemplate: '建议：普通人怎么做', contentRequirement: '给读者5条实用建议', wordRange: { min: 200, max: 400 }, required: true, fixedPhrases: ['给大家的建议', '如果你'] },
      { order: 5, stepName: '金句收尾', titleTemplate: '收尾：一句话展望', contentRequirement: '金句展望未来', wordRange: { min: 30, max: 100 }, required: true, fixedPhrases: ['新的一年', '一起'] },
      { order: 6, stepName: '感谢', titleTemplate: '感谢：谢谢你们', contentRequirement: '感谢读者的支持', wordRange: { min: 50, max: 100 }, required: false, fixedPhrases: ['谢谢', '感谢'] },
      { order: 7, stepName: '新年寄语', titleTemplate: '寄语：新的一年', contentRequirement: '新年祝福或寄语', wordRange: { min: 30, max: 80 }, required: false, fixedPhrases: ['愿', '新的一年'] },
    ],
    xiaohongshuStructure: [
      { order: 1, stepName: '年度回顾', titleTemplate: '年度回顾', contentRequirement: '精简行业变化', wordRange: { min: 40, max: 80 }, emojiSuggestions: ['📊', '📅'], shortSentence: true },
      { order: 2, stepName: '感悟+展望', titleTemplate: '感悟+展望', contentRequirement: '个人感悟+未来展望', wordRange: { min: 50, max: 100 }, emojiSuggestions: ['💭', '🔮'], shortSentence: false },
      { order: 3, stepName: '建议', titleTemplate: '新年建议', contentRequirement: '简短建议', wordRange: { min: 30, max: 60 }, emojiSuggestions: ['📌', '🎯'], shortSentence: true },
      { order: 4, stepName: '祝福收尾', titleTemplate: '祝福+标签', contentRequirement: '新年祝福+标签', wordRange: { min: 20, max: 60 }, emojiSuggestions: ['🎆', '❤️'], shortSentence: true },
    ],
    materialPositionMap: [
      { paragraphOrder: 1, stepName: '行业变化', materialTypes: ['data', 'case'], isPrimary: true },
      { paragraphOrder: 2, stepName: '个人感悟', materialTypes: ['personal_fragment', 'case'], isPrimary: true },
      { paragraphOrder: 3, stepName: '未来展望', materialTypes: ['data'], isPrimary: false },
      { paragraphOrder: 4, stepName: '给读者建议', materialTypes: ['fixed_phrase', 'analogy'], isPrimary: false },
      { paragraphOrder: 5, stepName: '金句收尾', materialTypes: ['golden_sentence'], isPrimary: true },
      { paragraphOrder: 6, stepName: '感谢', materialTypes: ['personal_fragment'], isPrimary: false },
      { paragraphOrder: 7, stepName: '新年寄语', materialTypes: ['golden_sentence'], isPrimary: false },
    ],
    emotionCurve: [
      { paragraphOrder: 1, stepName: '行业变化', emotion: '回顾', intensity: 6 },
      { paragraphOrder: 2, stepName: '个人感悟', emotion: '感慨', intensity: 7 },
      { paragraphOrder: 3, stepName: '未来展望', emotion: '期待', intensity: 6 },
      { paragraphOrder: 4, stepName: '给读者建议', emotion: '建议', intensity: 5 },
      { paragraphOrder: 5, stepName: '金句收尾', emotion: '温暖', intensity: 7 },
      { paragraphOrder: 6, stepName: '感谢', emotion: '感恩', intensity: 6 },
      { paragraphOrder: 7, stepName: '新年寄语', emotion: '希望', intensity: 7 },
    ],
    signaturePhrases: ['回顾这一年', '最大的变化', '我个人的感受', '给大家的建议', '新的一年'],
    sortOrder: 10,
    isActive: true,
    isSystem: true,
  },
];

/** 范式代码 → 中文名映射 */
export const PARADIGM_CODE_NAME_MAP: Record<string, string> = {
  P001: '标准错位破局范式',
  P002: '行业反思范式',
  P003: '案例归谬范式',
  P004: '本质定义范式',
  P005: '热点事件范式',
  P006: '产品解读范式',
  P007: '个人经历范式',
  P008: '避坑指南范式',
  P009: '对比分析范式',
  P010: '年终总结范式',
};

/** 范式代码 → 方案中对应文章类型映射 */
export const PARADIGM_ARTICLE_TYPE_MAP: Record<string, string> = {
  P001: '客户误区型',
  P002: '行业/政策解读',
  P003: '客户案例分析',
  P004: '保险概念科普',
  P005: '热点结合保险',
  P006: '产品测评',
  P007: '亲身经历分享',
  P008: '避坑干货',
  P009: '产品/方案对比',
  P010: '年度回顾',
};
