import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { sql } from 'drizzle-orm';

// GET /api/cases/manage - 查询案例列表
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const filter = searchParams.get('filter') || 'all'; // all | auto_tagged | needs_review | complete
    const keyword = searchParams.get('keyword') || '';
    const page = parseInt(searchParams.get('page') || '1');
    const pageSize = parseInt(searchParams.get('pageSize') || '20');

    // 构建筛选条件
    const conditions: any[] = [];

    if (keyword) {
      conditions.push(sql`(title ILIKE ${'%' + keyword + '%'} OR protagonist ILIKE ${'%' + keyword + '%'})`);
    }

    if (filter === 'needs_review') {
      conditions.push(sql`(product_tags::text LIKE '%待人工确认%' OR crowd_tags::text LIKE '%待人工确认%' OR emotion_tags::text LIKE '%待人工确认%')`);
    } else if (filter === 'auto_tagged') {
      conditions.push(sql`(metadata->>'autoGeneratedTags')::boolean = true`);
    } else if (filter === 'complete') {
      conditions.push(sql`(metadata->>'autoGeneratedTags')::boolean IS NOT TRUE`);
      conditions.push(sql`product_tags IS NOT NULL AND product_tags::text != '[]' AND product_tags::text != 'null'`);
      conditions.push(sql`(product_tags::text NOT LIKE '%待人工确认%')`);
    }

    const whereClause = conditions.length > 0
      ? sql`WHERE ${sql.join(conditions, sql` AND `)}`
      : sql``;

    // 查询总数
    const countResult = await db.execute(sql`
      SELECT COUNT(*) as total FROM industry_case_library ${whereClause}
    `);
    const countRows = Array.isArray(countResult) ? countResult : (countResult as any).rows || [];
    const total = Number(countRows[0]?.total || 0);

    // 查询数据
    const offset = (page - 1) * pageSize;
    const cases = await db.execute(sql`
      SELECT 
        id, title, protagonist, background, insurance_action, result,
        product_tags, crowd_tags, scene_tags, emotion_tags,
        use_count, metadata,
        created_at, updated_at
      FROM industry_case_library 
      ${whereClause}
      ORDER BY 
        CASE WHEN product_tags::text LIKE '%待人工确认%' THEN 0 ELSE 1 END,
        CASE WHEN (metadata->>'autoGeneratedTags')::boolean = true THEN 0 ELSE 1 END,
        use_count DESC NULLS LAST
      LIMIT ${pageSize} OFFSET ${offset}
    `);
    const caseRows = Array.isArray(cases) ? cases : (cases as any).rows || [];

    // 统计概览
    const statsResult = await db.execute(sql`
      SELECT 
        COUNT(*) as total,
        COUNT(*) FILTER (WHERE product_tags::text LIKE '%待人工确认%' OR crowd_tags::text LIKE '%待人工确认%' OR emotion_tags::text LIKE '%待人工确认%') as needs_review,
        COUNT(*) FILTER (WHERE (metadata->>'autoGeneratedTags')::boolean = true) as auto_tagged,
        COUNT(*) FILTER (WHERE protagonist IS NOT NULL AND protagonist != '') as has_content
      FROM industry_case_library
    `);
    const statsRows = Array.isArray(statsResult) ? statsResult : (statsResult as any).rows || [];

    return NextResponse.json({
      success: true,
      data: {
        cases: caseRows,
        total,
        page,
        pageSize,
        stats: statsRows[0] || {},
      },
    });
  } catch (error) {
    console.error('查询案例失败:', error);
    return NextResponse.json({ success: false, error: '查询案例失败' }, { status: 500 });
  }
}

// PUT /api/cases/manage - 更新案例标签
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, productTags, crowdTags, emotionTags, removeReviewTag } = body;

    if (!id) {
      return NextResponse.json({ success: false, error: '缺少案例ID' }, { status: 400 });
    }

    // 先获取当前案例数据
    const currentResult = await db.execute(sql`
      SELECT product_tags, crowd_tags, emotion_tags, metadata FROM industry_case_library WHERE id = ${id}
    `);
    const currentRows = Array.isArray(currentResult) ? currentResult : (currentResult as any).rows || [];
    if (currentRows.length === 0) {
      return NextResponse.json({ success: false, error: '案例不存在' }, { status: 404 });
    }

    let finalProductTags = productTags || currentRows[0].product_tags || [];
    let finalCrowdTags = crowdTags || currentRows[0].crowd_tags || [];
    let finalEmotionTags = emotionTags || currentRows[0].emotion_tags || [];
    let finalMetadata = currentRows[0].metadata || {};

    // 移除"待人工确认"标签
    if (removeReviewTag) {
      finalProductTags = (finalProductTags as string[]).filter(t => t !== '待人工确认');
      finalCrowdTags = (finalCrowdTags as string[]).filter(t => t !== '待人工确认');
      finalEmotionTags = (finalEmotionTags as string[]).filter(t => t !== '待人工确认');
      finalMetadata = { ...finalMetadata, autoGeneratedTags: false };
    }

    // 更新
    await db.execute(sql`
      UPDATE industry_case_library 
      SET 
        product_tags = ${JSON.stringify(finalProductTags)}::jsonb,
        crowd_tags = ${JSON.stringify(finalCrowdTags)}::jsonb,
        emotion_tags = ${JSON.stringify(finalEmotionTags)}::jsonb,
        metadata = ${JSON.stringify(finalMetadata)}::jsonb,
        updated_at = NOW()
      WHERE id = ${id}
    `);

    return NextResponse.json({ success: true, message: '标签更新成功' });
  } catch (error) {
    console.error('更新案例标签失败:', error);
    return NextResponse.json({ success: false, error: '更新标签失败' }, { status: 500 });
  }
}
