CREATE TABLE "agent_feedbacks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"feedback_id" text NOT NULL,
	"task_id" text NOT NULL,
	"from_agent_id" text NOT NULL,
	"to_agent_id" text NOT NULL,
	"original_command" text NOT NULL,
	"feedback_content" text NOT NULL,
	"feedback_type" text DEFAULT 'question' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"resolution" text,
	"resolved_command" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"resolved_at" timestamp,
	CONSTRAINT "agent_feedbacks_feedback_id_unique" UNIQUE("feedback_id")
);
--> statement-breakpoint
CREATE TABLE "agent_interactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"command_result_id" uuid NOT NULL,
	"task_description" text,
	"session_id" text NOT NULL,
	"sender" text NOT NULL,
	"receiver" text,
	"message_type" text NOT NULL,
	"content" text NOT NULL,
	"round_number" integer,
	"is_resolution" boolean DEFAULT false NOT NULL,
	"is_understand" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE TABLE "agent_memories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agent_id" text NOT NULL,
	"memory_type" text NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"importance" integer DEFAULT 0 NOT NULL,
	"source" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"notification_id" text NOT NULL,
	"from_agent_id" text NOT NULL,
	"to_agent_id" text NOT NULL,
	"notification_type" text NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"related_task_id" text,
	"status" text DEFAULT 'unread' NOT NULL,
	"priority" text DEFAULT 'normal' NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"is_read" boolean DEFAULT false NOT NULL,
	"read_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "agent_notifications_notification_id_unique" UNIQUE("notification_id")
);
--> statement-breakpoint
CREATE TABLE "agent_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_type" text NOT NULL,
	"command_result_id" uuid NOT NULL,
	"sub_task_id" uuid,
	"summary" text NOT NULL,
	"conclusion" text NOT NULL,
	"dialogue_process" jsonb NOT NULL,
	"suggested_actions" jsonb NOT NULL,
	"reported_to" text NOT NULL,
	"reported_from" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"reviewed_by" text,
	"reviewed_at" timestamp,
	"processed_by" text,
	"processed_at" timestamp,
	"processed_actions" jsonb DEFAULT '[]'::jsonb,
	"dismissed_reason" text,
	"related_task_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_sub_tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"command_result_id" uuid NOT NULL,
	"agent_id" text NOT NULL,
	"task_title" text NOT NULL,
	"task_description" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"order_index" integer NOT NULL,
	"started_at" timestamp,
	"completed_at" timestamp,
	"dialogue_session_id" text,
	"dialogue_rounds" integer DEFAULT 0 NOT NULL,
	"dialogue_status" text DEFAULT 'none' NOT NULL,
	"last_dialogue_at" timestamp,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" text NOT NULL,
	"task_name" text NOT NULL,
	"core_command" text NOT NULL,
	"executor" text NOT NULL,
	"acceptance_criteria" text NOT NULL,
	"task_type" text DEFAULT 'master' NOT NULL,
	"split_status" text DEFAULT 'pending' NOT NULL,
	"task_duration_start" timestamp NOT NULL,
	"task_duration_end" timestamp NOT NULL,
	"total_deliverables" text NOT NULL,
	"task_priority" text DEFAULT 'normal' NOT NULL,
	"task_status" text DEFAULT 'pending' NOT NULL,
	"creator" text NOT NULL,
	"updater" text DEFAULT 'TS' NOT NULL,
	"remarks" text,
	"from_agent_id" text NOT NULL,
	"to_agent_id" text NOT NULL,
	"command_type" text DEFAULT 'instruction' NOT NULL,
	"result" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	CONSTRAINT "agent_tasks_task_id_unique" UNIQUE("task_id")
);
--> statement-breakpoint
CREATE TABLE "command_results" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"command_id" text NOT NULL,
	"related_task_id" text NOT NULL,
	"command_content" text NOT NULL,
	"executor" text NOT NULL,
	"command_priority" text DEFAULT 'normal' NOT NULL,
	"execution_deadline_start" timestamp NOT NULL,
	"execution_deadline_end" timestamp NOT NULL,
	"deliverables" text NOT NULL,
	"execution_status" text DEFAULT 'new' NOT NULL,
	"status_proof" text,
	"help_record" text,
	"audit_opinion" text,
	"splitter" text DEFAULT 'agent B' NOT NULL,
	"entry_user" text DEFAULT 'TS' NOT NULL,
	"remarks" text,
	"last_ts_check_time" timestamp,
	"last_ts_awakening_time" timestamp,
	"ts_awakening_count" integer DEFAULT 0 NOT NULL,
	"last_inspection_time" timestamp,
	"last_consult_time" timestamp,
	"awakening_count" integer DEFAULT 0 NOT NULL,
	"task_type" text DEFAULT 'daily' NOT NULL,
	"execution_date" text,
	"is_confirmed" boolean DEFAULT false NOT NULL,
	"confirmed_by" text,
	"confirmed_at" timestamp,
	"rejection_reason" text,
	"dependencies" jsonb DEFAULT '{}',
	"sort_order" integer DEFAULT 0 NOT NULL,
	"task_id" text,
	"from_agent_id" text NOT NULL,
	"to_agent_id" text NOT NULL,
	"original_command" text NOT NULL,
	"execution_result" text,
	"output_data" jsonb DEFAULT '{}'::jsonb,
	"metrics" jsonb DEFAULT '{}'::jsonb,
	"attachments" jsonb DEFAULT '[]'::jsonb,
	"completed_at" timestamp,
	"scenario_type" text,
	"task_name" text,
	"trigger_source" text,
	"retry_status" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"completed_sub_tasks" integer DEFAULT 0 NOT NULL,
	"completed_sub_tasks_description" text,
	"sub_task_count" integer DEFAULT 0 NOT NULL,
	"question_status" text DEFAULT 'none' NOT NULL,
	"last_checked_at" timestamp,
	"last_inspected_at" timestamp,
	"dialogue_session_id" text,
	"dialogue_rounds" integer DEFAULT 0 NOT NULL,
	"dialogue_status" text DEFAULT 'none' NOT NULL,
	"last_dialogue_at" timestamp,
	"latest_report_id" uuid,
	"report_count" integer DEFAULT 0 NOT NULL,
	"requires_intervention" boolean DEFAULT false NOT NULL,
	CONSTRAINT "command_results_command_id_unique" UNIQUE("command_id")
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session_id" text NOT NULL,
	"user_id" text,
	"agent_id" text NOT NULL,
	"state" text DEFAULT 'active' NOT NULL,
	"variables" jsonb DEFAULT '{}'::jsonb,
	"context" jsonb DEFAULT '{}'::jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"ended_at" timestamp,
	"last_active_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "conversations_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"tokens" integer,
	"model" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "split_failures" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"failure_id" text NOT NULL,
	"task_id" text NOT NULL,
	"task_name" text NOT NULL,
	"core_command" text NOT NULL,
	"failure_reason" text NOT NULL,
	"retry_count" integer DEFAULT 0 NOT NULL,
	"agent_b_responses" jsonb DEFAULT '[]'::jsonb,
	"exception_status" text DEFAULT 'pending' NOT NULL,
	"exception_priority" text DEFAULT 'normal' NOT NULL,
	"assigned_to" text,
	"assigned_at" timestamp,
	"manual_split_result" jsonb DEFAULT '{}'::jsonb,
	"processing_notes" text,
	"resolved_by" text,
	"resolved_at" timestamp,
	"resolution_method" text,
	"resolution_result" jsonb DEFAULT '{}'::jsonb,
	"from_agent_id" text NOT NULL,
	"to_agent_id" text NOT NULL,
	"conversation_id" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "split_failures_failure_id_unique" UNIQUE("failure_id")
);
--> statement-breakpoint
ALTER TABLE "agent_interactions" ADD CONSTRAINT "agent_interactions_command_result_id_command_results_id_fk" FOREIGN KEY ("command_result_id") REFERENCES "public"."command_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_reports" ADD CONSTRAINT "agent_reports_command_result_id_command_results_id_fk" FOREIGN KEY ("command_result_id") REFERENCES "public"."command_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_reports" ADD CONSTRAINT "agent_reports_sub_task_id_agent_sub_tasks_id_fk" FOREIGN KEY ("sub_task_id") REFERENCES "public"."agent_sub_tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_sub_tasks" ADD CONSTRAINT "agent_sub_tasks_command_result_id_command_results_id_fk" FOREIGN KEY ("command_result_id") REFERENCES "public"."command_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "command_results" ADD CONSTRAINT "command_results_latest_report_id_agent_reports_id_fk" FOREIGN KEY ("latest_report_id") REFERENCES "public"."agent_reports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;